"""sync column types

Revision ID: cb091920077f
Revises: 99115725c0ab
Create Date: 2026-09-25 17:17:14.245895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb091920077f'
down_revision: Union[str, Sequence[str], None] = '99115725c0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'hour_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('shifts', 'date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False,
                postgresql_using='date::date')
    op.alter_column('shifts', 'hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('shifts', 'earned',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('shifts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shifts', 'earned',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('shifts', 'hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('shifts', 'date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False,
                postgresql_using='date::text')
    op.alter_column('settings', 'hour_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
